// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// joybus //
// ------ //

#define joybus_wrap_target 0
#define joybus_wrap 4

#define joybus_T1 10
#define joybus_T2 20
#define joybus_T3 10

#define joybus_offset_read 0u

static const uint16_t joybus_program_instructions[] = {
            //     .wrap_target
    0xe080, //  0: set    pindirs, 0                 
    0x3320, //  1: wait   0 pin, 0               [19]
    0x4001, //  2: in     pins, 1                    
    0x20a0, //  3: wait   1 pin, 0                   
    0x0001, //  4: jmp    1                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program joybus_program = {
    .instructions = joybus_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config joybus_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + joybus_wrap_target, offset + joybus_wrap);
    return c;
}

#include <hardware/clocks.h>
static inline pio_sm_config joybus_program_get_config(PIO pio, uint sm, uint offset, uint pin) {
    pio_gpio_init(pio, pin);
    pio_sm_config c = joybus_program_get_default_config(offset);
    sm_config_set_set_pins(&c, pin, 1);
    sm_config_set_in_pins(&c, pin);
    // Shift to left, no autopull, 9 bit
    sm_config_set_in_shift(&c, false, true, 9);
    int cycles_per_bit = joybus_T1 + joybus_T2 + joybus_T3;
    int bitrate = 250000;
    float div = clock_get_hz(clk_sys) / (cycles_per_bit * bitrate);
    sm_config_set_clkdiv(&c, div);
    return c;
}
static inline void joybus_program_receive_init(
    PIO pio,
    uint sm,
    uint offset,
    uint pin,
    pio_sm_config *c
) {
    pio_sm_init(pio, sm, offset + joybus_offset_read, c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif
